### ISSUE TITLE
How to deal with varying object scale?

### ISSUE THREAD

**Issue by mrgloom** [WeidiXie/cell_counting_v2#2]
![klhad](https://cloud.githubusercontent.com/assets/4003908/26623109/5729e7f0-45f5-11e7-819c-d197695ec6a2.jpg)

Any ideas how to deal with varying object scale? Putting gaussian with fixed sigma in not very good solution when scale of object is different across image?

**Comment by WeidiXie** [comment]
In my opinion, what you can try is to add more augmentation on image scales, for instance zooming in, and zooming out. Also, instead of 64 channels in my code, use FCRN with skip layers or U-Net with more channels, 

Essentially, there's not much appearance difference over the image, you only need to train the model to be robust (invariant) to the scaling factor, 

Once finishing training, you can evaluate on images of multi-scale, and then average all the predictions.

BW
Weidi

**Comment by WeidiXie** [comment]
Oh, also, maybe deeper networks, because I don't know how large your images are, you need to guarantee the receptive field of the network is large enough to at least cover the largest objects in your image.

**Comment by mrgloom** [comment]
I understand that at training time I can rescale image to make crops at different scales to perform data augmentation and at prediction time I do prediction at different scales and then combine results, but my question is about ground truth density map creation: if I have point coordinates that are at center of object and objects on single image have different scale, then I can't put gaussian with same sigma at each center point, because some big objects will be not fully convered and some small objects will be covered capturing also background.

Also as separate question maybe you have ideas how to estimates diameter of object? maybe some type of regression in the form center point (x,y) + diameter/radius?

**Comment by WeidiXie** [comment]
Have you tried to do that (put single scale Gaussian on objects of all scales)?

In my opinion, it doesn't matter if the Gaussian can cover the whole object or not, 
as I can tell from the image you send, it is pretty straight-forward to detect the center of the objects,
because there's no overlap, and not much appearance change.

The only thing for the networks to deal with is the scale variance of the objects, which can be dealt with extreme data augmentation on scales.

Weidi

**Comment by WeidiXie** [comment]
Hi,

**Comment by WeidiXie** [comment]
How is it going with this problem ?

Have you solved it already ?
 
Can I close this now ?
